version: '2'
services:
  api-postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - '5432:5432'
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql